### ISSUE TITLE
大佬，能帮帮忙吗？

### ISSUE THREAD

**Issue by Nododo** [SmileZXLee/ZXRequestBlock#12]
thor 已下架，无法购买了，给我分享账号下载一下吗？

感谢了。

买都买不到，真够难受的。

**Comment by SmileZXLee** [comment]
可以下stream，功能和thor差不多

**Comment by SmileZXLee** [comment]
我目前用的也是stream了

**Comment by Nododo** [comment]
> 可以下stream，功能和thor差不多

好的  多谢

**Comment by SmileZXLee** [comment]
> > 可以下stream，功能和thor差不多
> 
> 好的 多谢

不客气
