### ISSUE TITLE
crash 原因-[NSURLSessionConfiguration disposition] unrecognized selector

### ISSUE THREAD

**Issue by rtcatc** [SmileZXLee/ZXRequestBlock#14]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSURLSessionConfiguration disposition]: unrecognized selector sent to instance 0x2839e96c0'
*** First throw call stack:
(0x1bcd1498c 0x1bca3d0a4 0x1bcc1843c 0x1bcd18e08 0x1bcd1abec 0x1bff0ede4 0x10d508380 0x10d508468 0x105dbd160 0x1bca44ecc 0x10767a0d4 0x10768958c 0x107688308 0x1076883d0 0x10767a420 0x10767edb4 0x107679208 0x107679038)

**Comment by rtcatc** [comment]
版本 ios 13.1.2

**Comment by rtcatc** [comment]
我把
ZXRequestBlock/NSURLSession+ZXHttpProxy.m内的
`configuration = [[NSURLSessionConfiguration alloc] init];`
改成了
`configuration = [NSURLSessionConfiguration defaultSessionConfiguration];`
就可以了（参考：https://github.com/lionheart/openradar-mirror/issues/7707）
但不知道会不会产生其他问题，待测试

**Comment by rtcatc** [comment]
对MobileSafari (系统浏览器hook测试无问题)
我将提pull request上来
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/15169833/224066801-5986ce0a-abb6-47d8-9def-ef944ce88c2d.png">
<img width="811" alt="image" src="https://user-images.githubusercontent.com/15169833/224066868-a9d8dc1c-4a54-48e7-b406-e8e6e832415b.png">

**Comment by SmileZXLee** [comment]
感谢mr

**Comment by SmileZXLee** [comment]
感谢pr!
