### ISSUE TITLE
请教下 有办法抓取第三方app数据吗

### ISSUE THREAD

**Issue by looha518** [SmileZXLee/ZXRequestBlock#4]

**Comment by 1json** [comment]
您可以使用Charles、Wireshark、Thor的应用，通过网络代理的方式抓取第三方App的数据。

**Comment by SmileZXLee** [comment]
您可以使用Charles、Wireshark、Thor的应用，通过网络代理的方式抓取第三方App的数据。

**Comment by looha518** [comment]
我们的项目有个需求，需要类似Thor的抓包功能

**Comment by 1json** [comment]
> 我们的项目有个需求，需要类似Thor的抓包功能

需要做一个 抓包工具吗

**Comment by looha518** [comment]
Network Extension 搭建了隧道，走了代理，获取到data,但是访问不了网络了，大佬可以给个思路吗

**Comment by looha518** [comment]
> > 我们的项目有个需求，需要类似Thor的抓包功能
> 
> 需要做一个 抓包工具吗

嗯 对的

**Comment by SmileZXLee** [comment]
可以使用

> Network Extension 搭建了隧道，走了代理，获取到data,但是访问不了网络了，大佬可以给个思路吗

需要自己组包，转发出去

**Comment by looha518** [comment]
> 您可以使用Charles、Wireshark、Thor的应用，通过网络代理的方式抓取第三方App的数据。

Network Extension 搭建了隧道，走了代理，获取到data,但是访问不了网络了，大佬可以给个思路吗

**Comment by SmileZXLee** [comment]
> > 您可以使用Charles、Wireshark、Thor的应用，通过网络代理的方式抓取第三方App的数据。
> 
> Network Extension 搭建了隧道，走了代理，获取到data,但是访问不了网络了，大佬可以给个思路吗

需要自己组包，转发出去

**Comment by looha518** [comment]
> > > 您可以使用Charles、Wireshark、Thor的应用，通过网络代理的方式抓取第三方App的数据。
> > 
> > 
> > Network Extension 搭建了隧道，走了代理，获取到data,但是访问不了网络了，大佬可以给个思路吗
> 
> 需要自己组包，转发出去

好的 谢谢 我研究下自己组包方向
