### ISSUE TITLE
开启防代理抓包云信im消息图片 语音 发送失败

### ISSUE THREAD

**Issue by Lifei0229** [SmileZXLee/ZXRequestBlock#5]
Task <33422CEA-CA34-4031-92C2-49A16CF59C23>.<1> finished with error [-1202] Error Domain=NSURLErrorDomain Code=-1202 "此服务器的证书无效。您可能正在连接到一个伪装成“45.127.129.8”的服务器，这会威胁到您的机密信息的安全。" UserInfo={NSLocalizedRecoverySuggestion=您仍要连接此服务器吗？, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=	(
	<cert(0x1130a4400) s: *.127.net i: GeoTrust CN RSA CA G1>,
	<cert(0x1130a4e00) s: GeoTrust CN RSA CA G1 i: DigiCert Global Root CA>,
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://45.127.129.8/nim/MTY4MzY2Mzg%3D%2FbmltYV8yMTg2NTQxNzc0NV8xNjA1OTMwMjM4MjM1XzBlZDJkOTUzLTY1MjktNGRlYy05NDJmLTk0OGExN2MzYmIwYQ%3D%3D?offset=0&complete=true&version=1.0, NSErrorFailingURLStringKey=https://45.127.129.8/nim/MTY4MzY2Mzg%3D%2FbmltYV8yMTg2NTQxNzc0NV8xNjA1OTMwMjM4MjM1XzBlZDJkOTUzLTY1MjktNGRlYy05NDJmLTk0OGExN2MzYmIwYQ%3D%3D?offset=0&complete=true&version=1.0, NSUnderlyingError=0x13df4d990 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x13d0a9d30>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9843, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9843, kCFStreamPropertySSLPeerCertificates=	(
	<cert(0x1130a4400) s: *.127.net i: GeoTrust CN RSA CA G1>,
	<cert(0x1130a4e00) s: GeoTrust CN RSA CA G1 i: DigiCert Global Root CA>,
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=	(
	"LocalDataTask <33422CEA-CA34-4031-92C2-49A16CF59C23>.<1>",
), _kCFStreamErrorCodeKey=-9843, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <33422CEA-CA34-4031-92C2-49A16CF59C23>.<1>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x13d0a9d30>, NSLocalizedDescription=此服务器的证书无效。您可能正在连接到一个伪装成“45.127.129.8”的服务器，这会威胁到您的机密信息的安全。}

**Comment by SmileZXLee** [comment]
是否设置了`[ZXRequestBlock enableHttpDns];`，若设置了，需要注释掉这一行。

**Comment by Lifei0229** [comment]
> 是否设置了`[ZXRequestBlock enableHttpDns];`，若设置了，需要注释掉这一行。

没有设置。只要pod 'ZXRequestBlock' 安装这个库  就不行了。什么都不设置 就出现上面的错误

**Comment by SmileZXLee** [comment]
您好，我下载了云信im的demo进行测试，当不安装`ZXRequestBlock`就有“此服务器的证书无效。您可能正在连接到一个伪装成“lbs.netease.im”的服务器，这会威胁到您的机密信息的安全。”的提示，但不影响正常请求，当我安装`ZXRequestBlock`后，对正常的请求无任何影响，设置`[ZXRequestBlock disableHttpProxy];`后是用抓包工具无法抓包，对demo正常请求仍无任何影响。

**Comment by Lifei0229** [comment]
谢谢了。已解决。更新了云信的sdk 好了。。。
